# Generated by Django 5.2.6 on 2025-09-30 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_filiere_user_niveau'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='etablissement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='etudiants', to='users.etablissementprofile'),
            preserve_default=False,
        ),
    ]
