# Generated by Django 5.2.6 on 2025-10-04 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_etablissement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='etablissement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='etudiants', to='users.etablissementprofile'),
        ),
    ]
