services:
  - type: web
    name: backend
    env: python
    plan: free
    region: oregon
    branch: main
    buildCommand: |
      pip install -r requirements.txt &&
      python manage.py migrate &&
      python manage.py collectstatic --noinput
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: NEON_DATABASE
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: DJANGO_DEBUG
        value: "0"
        sync: false
      - key: CORS_ALLOW_ALL
        value: "1"
        sync: false
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
