services:
  - type: web
    name: backend
    env: python
    plan: free
    region: oregon
    branch: main
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        sync: false   # ⚠️ doit être défini dans le dashboard Render avec l’URL Neon
      - key: DJANGO_DEBUG
        value: "0"
      - key: CORS_ALLOW_ALL
        value: "1"
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
