services:
  - type: web
    name: backend
    env: python
    plan: free
    region: oregon
    branch: main
    buildCommand: |
      rm -rf staticfiles
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: DJANGO_DEBUG
        value: "0"
        sync: false
      - key: CORS_ALLOW_ALL
        value: "1"
        sync: false
