services:
  - type: web
    name: backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "daphne config.asgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
