services:
  - type: web
    name: backend
    env: python
    plan: free
    region: oregon
    branch: main
    buildCommand: >
      pip install -r requirements.txt &&
      python manage.py migrate &&
      python manage.py collectstatic --noinput
    startCommand: gunicorn config.wsgi:application
    envVars:
      # Database
      - key: DATABASE_URL
        sync: false
      # Django secret key
      - key: SECRET_KEY
        sync: false
      # Debug mode: False en prod
      - key: DEBUG
        value: "False"
        sync: false
      # Frontend origin pour CORS (si tu as un frontend sur un autre domaine)
      - key: CORS_ALLOWED_ORIGINS
        value: "https://data-fit-frontend.vercel.app/"
        sync: false
