# Generated by Django 5.2.6 on 2025-09-22 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programmes', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=20)),
                ('tuteur_prenom', models.CharField(blank=True, max_length=100, null=True)),
                ('tuteur_nom', models.CharField(blank=True, max_length=100, null=True)),
                ('tuteur_telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('motivation', models.TextField()),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('acceptee', 'Acceptée'), ('rejettee', 'Rejetée')], default='en_attente', max_length=20)),
                ('date_postule', models.DateTimeField(auto_now_add=True)),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to='users.etablissementprofile')),
                ('filiere', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='programmes.filiere')),
                ('niveau', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='programmes.niveau')),
            ],
        ),
    ]
