# Generated by Django 5.2.6 on 2025-09-23 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postuler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='phs',
            field=models.BooleanField(default=False),
        ),
    ]
