# Generated by Django 5.2.6 on 2025-09-22 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programmes', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filiere',
            name='etablissement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filieres', to='users.etablissementprofile'),
        ),
        migrations.AddField(
            model_name='niveau',
            name='etablissement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niveaux', to='users.etablissementprofile'),
        ),
    ]
