# Generated by Django 5.2.6 on 2025-09-22 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FichierImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='uploads/')),
                ('nom', models.CharField(blank=True, max_length=255)),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
