# Generated by Django 5.2.6 on 2025-09-22 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importFichier', '0002_departement_centre_filiere_niveau'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichierimport',
            name='uploaded_by',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='imports', to='users.etablissementprofile'),
            preserve_default=False,
        ),
    ]
